title: Insights Operator Mock
description: HTTP server mock for https://github.com/tisnik/insights-operator-controller
baseurl: "/insights-operator-mock"
url: "https://tisnik.github.io"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/tisnik/insights-operator-mock"

footer_content: "Copyright &copy; Pavel Tisnovsky</a>"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
